project:
  type: website

website:
  title: "Amaan J. Sattar"
  navbar:
    right:
      - text: "CV"
        href: cv.qmd
      - text: "Blog"
        href: blog.qmd
      - icon: github
        href: https://github.com/amaanjsattar

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.5.0/css/all.css">
